### ISSUE TITLE
archetypes dir 외의 다른 dir에서는 main 뷰로 뜨지 않는 문제

### ISSUE THREAD

**Issue by newdeal123** [Network-Leader/Network-Leader.github.io#1]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/31841502/181244271-e28dfdcd-b896-4a9c-9fc9-79337df9c5ae.png">

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/31841502/181244234-00dfe0ba-3bc4-4710-a85c-8d1b2fe6d2cd.png">

메인페이지에서 archetypes 폴더에 담긴 .md 파일만 메인 뷰에서 뜨는 문제가 발생.

**Comment by newdeal123** [comment]
아니면 모든 콘텐츠를 archetypes dir에 넣어야 하는지?

**Comment by TProgramer** [comment]
content 폴더 안에서 post(.md) 파일들을 모아둔 하나의 하위폴더에서만 불러오는 것으로 보여요
post 게시할 때 경로를 posts 폴더 안으로만 해주시고, posts 폴더 안에서는 어느 경로로든 불러와지는걸로 보이네요
추가로 post 게시방식을 README 파일에서 수정할게요!
